[lint]
select = [
    "F",
    "I",  # isort
    "N", # pep8-naming (N)
    "UP", # pyupgrade (UP)
]

ignore = ["D107", "D415", "D104", "N806", "ANN101", "N803"]

[lint.pydocstyle]
convention = "google"
