AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda



# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:

  MusicFlowAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: Hello World API
      StageName: Prod

  MusicFlowFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        MusicFlow:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MusicFlowAPI
            Path: /
            Method: get
        Docs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MusicFlowAPI
            Path: /docs
            Method: get


    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

# Outputs:
#   ApiUrl:
#     Description: URL of your API
#     Value:
#       Fn::Sub: 'https://${MusicFlowAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MusicFlowAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${MusicFlowAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  MusicFlowFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt MusicFlowFunction.Arn
  MusicFlowFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MusicFlowFunctionRole.Arn
