name: Run API tests

on: [push]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3

      - name: Install python version 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          # cache: 'pip' # caching pip dependencies

      - name: install all dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Create env file
        run: |
          touch .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          cat .env
      
      - name: test with pytest
        run: |
          python -m pytest
